// Generated by gencpp from file nanyageev_ir_13345_2_2/QuadraticEquationSolverRequest.msg
// DO NOT EDIT!


#ifndef NANYAGEEV_IR_13345_2_2_MESSAGE_QUADRATICEQUATIONSOLVERREQUEST_H
#define NANYAGEEV_IR_13345_2_2_MESSAGE_QUADRATICEQUATIONSOLVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nanyageev_ir_13345_2_2
{
template <class ContainerAllocator>
struct QuadraticEquationSolverRequest_
{
  typedef QuadraticEquationSolverRequest_<ContainerAllocator> Type;

  QuadraticEquationSolverRequest_()
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
    }
  QuadraticEquationSolverRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QuadraticEquationSolverRequest_

typedef ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<std::allocator<void> > QuadraticEquationSolverRequest;

typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest > QuadraticEquationSolverRequestPtr;
typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest const> QuadraticEquationSolverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nanyageev_ir_13345_2_2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ffac936c9b4e668039d250d853dc9b2";
  }

  static const char* value(const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ffac936c9b4e668ULL;
  static const uint64_t static_value2 = 0x039d250d853dc9b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nanyageev_ir_13345_2_2/QuadraticEquationSolverRequest";
  }

  static const char* value(const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n\
float64 b\n\
float64 c\n\
";
  }

  static const char* value(const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadraticEquationSolverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NANYAGEEV_IR_13345_2_2_MESSAGE_QUADRATICEQUATIONSOLVERREQUEST_H
