// Generated by gencpp from file nanyageev_ir_13345_2_2/QuadraticEquationSolverResponse.msg
// DO NOT EDIT!


#ifndef NANYAGEEV_IR_13345_2_2_MESSAGE_QUADRATICEQUATIONSOLVERRESPONSE_H
#define NANYAGEEV_IR_13345_2_2_MESSAGE_QUADRATICEQUATIONSOLVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nanyageev_ir_13345_2_2
{
template <class ContainerAllocator>
struct QuadraticEquationSolverResponse_
{
  typedef QuadraticEquationSolverResponse_<ContainerAllocator> Type;

  QuadraticEquationSolverResponse_()
    : answer()  {
    }
  QuadraticEquationSolverResponse_(const ContainerAllocator& _alloc)
    : answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QuadraticEquationSolverResponse_

typedef ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<std::allocator<void> > QuadraticEquationSolverResponse;

typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse > QuadraticEquationSolverResponsePtr;
typedef boost::shared_ptr< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse const> QuadraticEquationSolverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nanyageev_ir_13345_2_2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7e708f879c94bb931716d8f4f130f30";
  }

  static const char* value(const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7e708f879c94bb9ULL;
  static const uint64_t static_value2 = 0x31716d8f4f130f30ULL;
};

template<class ContainerAllocator>
struct DataType< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nanyageev_ir_13345_2_2/QuadraticEquationSolverResponse";
  }

  static const char* value(const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string answer\n\
\n\
";
  }

  static const char* value(const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadraticEquationSolverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nanyageev_ir_13345_2_2::QuadraticEquationSolverResponse_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NANYAGEEV_IR_13345_2_2_MESSAGE_QUADRATICEQUATIONSOLVERRESPONSE_H
